# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/golangci/golangci-lint.git
    rev: v1.43.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        files: ^2021/
        description: Fast linters runner for Go.
        entry: bash -c 'cd 2021; golangci-lint run --fix'
        types: [go]
        language: golang
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
